title_name = "Tony Hawk Pro Skater 5"
title_id = "4156091B" # AV-2331
#hash = "" # default.xex
#media_id = "64C2415F"

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x82
        value = 0x01
