title_name = "Man vs. Wild"
title_id = "435607D9" # CV-2009
hash = "324FCEDFC383874D" # Default.xex

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = true

    [[patch.be8]]
        address = 0x822BE743
        value = 0x01
    [[patch.be8]]
        address = 0x822BE757
        value = 0x01
