title_name = "Man vs. Wild"
title_id = "435607D9" # CV-2009
hash = "5B385BCAF7065309" # default.xex
#media_id = "30B5141E"

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x822be743
        value = 0x01
    [[patch.be8]]
        address = 0x822be757
        value = 0x01
