title_name = "Man vs. Wild"
title_id = "435607D9" # CV-2009
#hash = "" # default.xex
#media_id = "30B5141E"

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = true

    [[patch.be8]]
        address = 0x822BE743
        value = 0x01
    [[patch.be8]]
        address = 0x822BE757
        value = 0x01
