title_name = "Battlefield: Bad Company"
title_id = "454107F9" # EA-2041
hash = "710846641A90AC15" # default.xex
#media_id = "75F7BA6A"

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x821603d7
        value = 0x01
