title_name = "Forza Horizon 2"
title_id = "4D530AA4" # MS-2724
#hash = "" # default.xex
#media_id = "7C7779D1" http://redump.org/disc/60608/

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x82B71D4B
        value = 0x00
    [[patch.be8]]
        address = 0x82B71D37
        value = 0x00
