title_name = "Forza Motorsport 4"
title_id = "4D530910" # MS-2320
hash = "AE792356E8071FF6" # default.xex
#media_id = "33E7B39F"

[[patch]]
    name = "Square Shadow Fix"
    author = "illusion"
    is_enabled = false

    [[patch.be8]]
        address = 0x828df12b
        value = 0x01

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x822b2f4f
        value = 0x01
    [[patch.be8]]
        address = 0x822b2f63
        value = 0x01
