title_name = "Kinect Star Wars"
title_id = "4D53090E" # MS-2318
hash = "1DA5376FD736C512" # default.xex
#media_id = "0967FCD4"

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x82454bbb
        value = 0x01

[[patch]]
    name = "1280x720 Resolution"
    author = "Margen67"
    is_enabled = false

#    [[patch.be16]]
#        address = 0x822583de
#        value = 0x0500
#    [[patch.be16]]
#        address = 0x822583e2
#        value = 0x02d0
    [[patch.be16]] # Breaks rendering
        address = 0x822583fa # Breaks rendering
        value = 0x0500 # Breaks rendering
    [[patch.be16]] # Breaks rendering
        address = 0x822583fe # Breaks rendering
        value = 0x02d0 # Breaks rendering
#    [[patch.be16]]
#        address = 0x8231747b
#        value = 0x02d0
#    [[patch.be16]]
#        address = 0x823174bb
#        value = 0x0500
#    [[patch.be16]]
#        address = 0x8232ec40
#        value = 0x02d0
#    [[patch.be16]]
#        address = 0x8232ec98
#        value = 0x0500
#    [[patch.be16]]
#        address = 0x8281d40a
#        value = 0x02d0
#    [[patch.be16]]
#        address = 0x8281d42e
#        value = 0x02d0
#    [[patch.be16]]
#        address = 0x8281d45a
#        value = 0x0500
#    [[patch.be16]]
#        address = 0x828b79a2
#        value = 0x02d0
#    [[patch.be16]]
#        address = 0x828b79aa
#        value = 0x0500
#    [[patch.be16]]
#        address = 0x829ff37a
#        value = 0x0500
#    [[patch.be16]]
#        address = 0x829ff3d6
#        value = 0x02d0
    [[patch.be16]] # Real
        address = 0x82a5929a # Real
        value = 0x0500 # Real
    [[patch.be16]] # Real
        address = 0x82a5929e # Real
        value = 0x02d0 # Real
#    [[patch.be16]]
#        address = 0x82b30d81
#        value = 0x0500
#    [[patch.be16]]
#        address = 0x82b30dce
#        value = 0x02d0
