title_name = "Fable II" # フェイブルⅡ, 2
title_id = "4D5307F1" # MS-2033
hash = "42FFBA85DA590339" # default.xex
#media_id = [
#    "04BF96A1", # Disc (Italy):       http://redump.org/disc/57018
#    "21DFA75E", # Disc (Spain):       http://redump.org/disc/72052
#    "28173C4E", # Disc (Japan):       http://redump.org/disc/75492
#    "6473199D", # Disc (USA, Europe): http://redump.org/disc/12484
#    "6BC95506", # Disc (Russia):      http://redump.org/disc/75396
#]

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x82b6422b
        value = 0x01

[[patch]]
    name = "1280x720 Resolution"
    desc = "Original resolution is 1120x720."
    author = "Margen67"
    is_enabled = false

    [[patch.be16]]
        address = 0x82311d9a
        value = 0x0500

[[patch]]
    name = "Disable MSAA (Multi-Sample Anti-Aliasing)"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x82311d7f
        value = 0x01
