title_name = "Ninja Gaiden II" # 2
title_id = "544307D5" # TC-2005
hash = "AFF931BFF00F8A0A" # default.xex
#media_id = [
#    "69F555CB", # Disc (World): http://redump.org/disc/13299
#    "0E6FB1CE", # Disc (Japan): http://redump.org/disc/93943
#]

[[patch]]
    name = "1280x720 Resolution"
    desc = "Original resolution is 1120x584."
    author = "Margen67"
    is_enabled = true

    [[patch.be16]]
        address = 0x836261e6
        value = 0x02d0
    [[patch.be16]]
        address = 0x837c62fe
        value = 0x02d0
    [[patch.be16]]
        address = 0x836261ea
        value = 0x0500
    [[patch.be16]]
        address = 0x837c62fa
        value = 0x0500

[[patch]] 
    name = "Skip Chapter 12 crash Base version"
    desc = "Causes issues outside of ch12, so is disabled by default, use it only to skip the crash in ch12."
    author = "Gliniak"
    is_enabled = false

    [[patch.be32]]
        address = 0x82834c78
        value = 0x3bc00000