title_name = "Naruto: Rise of a Ninja"
title_id = "555307E5" # US-2021
#hash = "" # default.xex
#media_id = ""

[[patch]]
    name = "60 FPS"
    desc = "Speeds up the game."
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x821385E7
        value = 0x01
